export default defineAppConfig({
  pages: [
    "pages/index/index",
    "pages/my/index",
    "pages/my/my-posts/my-posts",
    "pages/publish/index",
    "pages/detail/index",
    "pages/post/index",
    "pages/post/form/index",
    "pages/my-posts/index",
    "pages/my/edit-nickname/index",
    "pages/my/favorites/index",
    "pages/settings/about/index",
    "pages/settings/help-feedback/index",
    "pages/settings/user-agreement/index",
    "pages/settings/privacy-policy/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black",
    enablePullDownRefresh: true,
  },
  tabBar: {
    color: "#999",
    selectedColor: "#007AFF",
    backgroundColor: "#fff",
    borderStyle: "black",
    list: [
      {
        pagePath: "pages/index/index",
        text: "首页",
        iconPath: "assets/icons/home.png",
        selectedIconPath: "assets/icons/home-active.png",
      },
      {
        pagePath: "pages/post/index",
        text: "发布",
        iconPath: "assets/icons/post.png",
        selectedIconPath: "assets/icons/post-active.png",
      },
      {
        pagePath: "pages/my/index",
        text: "我的",
        iconPath: "assets/icons/profile.png",
        selectedIconPath: "assets/icons/profile-active.png",
      },
    ],
  },
});
